# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5RVfP0Dr_rs7bPqf1WQjU6F5MbmaeyU
"""

a=int(input())
b=int(input())
c=int(input())
total=a+b+c
if (total>50):
  total=0.9*total
  print("Total cost= ",total)
else:
  print("Total cost= ",total)